# Phase 3 : Deep Learning - Comparaison d'architectures
On teste trois reseaux de neurones differents. Les performances sont presentees dans des tableaux Pandas.

In [ ]:
import pandas as pd
import pickle
import os
import sys
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
sys.path.append(os.path.abspath('..'))
from src.data_loader import load_yelp_sample

vec = pickle.load(open('../models/vectorizer.pkl', 'rb'))
df = load_yelp_sample('../data/raw/review.json', n_rows=50000)
df['label'] = (df['stars'] <= 2).astype(int)
X = vec.transform(df['text'])
y = df['label']

Chargement de 50000 lignes depuis ../data/raw/review.json...

### Architecture 1 : Standard (64, 32)

In [ ]:
mlp1 = MLPClassifier(hidden_layer_sizes=(64, 32), early_stopping=True, random_state=42)
mlp1.fit(X, y)
report_m1 = classification_report(y, mlp1.predict(X), output_dict=True)
display(pd.DataFrame(report_m1).transpose().round(2))

              precision  recall  f1-score   support
0                  0.97    0.96      0.96  40618.00
1                  0.83    0.85      0.84   9382.00
accuracy           0.94    0.94      0.94      0.94
macro avg          0.90    0.91      0.90  50000.00
weighted avg       0.94    0.94      0.94  50000.00

### Architecture 2 : Profonde (128, 64, 32)

In [ ]:
mlp2 = MLPClassifier(hidden_layer_sizes=(128, 64, 32), early_stopping=True, random_state=42)
mlp2.fit(X, y)
report_m2 = classification_report(y, mlp2.predict(X), output_dict=True)
display(pd.DataFrame(report_m2).transpose().round(2))

              precision  recall  f1-score   support
0                  0.98    0.98      0.98  40618.00
1                  0.90    0.90      0.90   9382.00
accuracy           0.96    0.96      0.96      0.96
macro avg          0.94    0.94      0.94  50000.00
weighted avg       0.96    0.96      0.96  50000.00

### Architecture 3 : Large (256)

In [ ]:
mlp3 = MLPClassifier(hidden_layer_sizes=(256,), early_stopping=True, random_state=42)
mlp3.fit(X, y)
report_m3 = classification_report(y, mlp3.predict(X), output_dict=True)
display(pd.DataFrame(report_m3).transpose().round(2))
pickle.dump(mlp1, open('../models/deep_model.pkl', 'wb'))

              precision  recall  f1-score   support
0                  0.95    0.97      0.96  40618.00
1                  0.85    0.80      0.83   9382.00
accuracy           0.94    0.94      0.94      0.94
macro avg          0.90    0.88      0.89  50000.00
weighted avg       0.94    0.94      0.94  50000.00